# Generated by Django 3.1.2 on 2020-10-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ov_name', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=300)),
                ('user_name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('api_version', models.IntegerField()),
                ('source_SPT_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Spt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spt_data', models.TextField()),
                ('ov_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPTClone.config')),
            ],
        ),
    ]
